# Generated by Django 5.0 on 2024-01-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('image', models.CharField(max_length=50)),
                ('content', models.CharField()),
                ('excerpt', models.CharField()),
                ('slug', models.CharField()),
            ],
        ),
    ]
